version: '3'
volumes:
  dados:
services:
  db:
    image: postgres:9.6
    volumes:
      - dados:/var/lib/postgresql/data
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=root
      - PASTGRES_PASSWORD=123123
  frontend:
    image: nginx:1.13
    volumes:
      - ./front:/usr/share/nginx/html/
    ports:
      - 80:80
  web:
    build: .
    ports:
      - 5000:5000
    volumes: ['.:/app']